# Generated by Django 6.0.6 on 2026-07-15 12:28

import videos_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0002_alter_video_options_video_processing_error_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=videos_app.models.video_thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Documentary', 'Documentary'), ('Drama', 'Drama'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('History', 'History'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Nature', 'Nature'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction'), ('Sports', 'Sports'), ('Thriller', 'Thriller'), ('Travel', 'Travel')], max_length=100),
        ),
    ]
